### ISSUE TITLE
LSTM predict

### ISSUE THREAD

**Issue by quant2016** [VivekPa/AIAlpha#12]

**Comment by quant2016** [comment]
i use model.py to predict price and get same prediction value

**Comment by VivekPa** [comment]
yes, it is an issue when training the model as the model converges to a local minima. I would suggest alterning the parameters and changing the weight initialization

**Comment by TIANRENK** [comment]
> yes, it is an issue when training the model as the model converges to a local minima. I would suggest alterning the parameters and changing the weight initialization

I have the same problem. And  how to alterning the parameters and changing the weight initialization ?
