### ISSUE TITLE
download() missing 1 required positional argument: 'tickers'

### ISSUE THREAD

**Issue by Johk3** [VivekPa/AIAlpha#18]
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from get_data import GetData
  File "/root/DeepMarket/Numerical/AIAlpha/get_data.py", line 3, in <module>
    fix.pdr_override()
TypeError: download() missing 1 required positional argument: 'tickers'

**Comment by VivekPa** [comment]
You were supposed to input which tickers you want to download data for. But now that function doesn’t exist, as yahoo finance api is not functional.

**Comment by wa1era** [comment]
Do not tell me, did he completely stop working? for what reason?

**Comment by davex9000** [comment]
Damn facing the same issue here. had no idea that they discontinued the library.
