### ISSUE TITLE
Run fails on a clean freshly downloaded project

### ISSUE THREAD

**Issue by assaf-b** [VivekPa/AIAlpha#20]
Hi,

First, thanks for posting this code.

The project has been downloaded as a zip file.  At the beginning of the run it exits with an error about a missing dollar_bars.csv
Searching dollar_bars.csv finds 3 references.   2 in run.py/run_full.py sources, that immediately read it via some function, and fail.  And 1 in bar_sample.py.  But running bar_sample.py fails, since price_vol.csv is missing.

Searching price_vol.csv finds 3 read references from bar_sample.py itself, 1 read reference in test.py, and 1 write reference in test.py, BUT it relies on reading the file first.  So no actual write references that *create* this file.

Hence, a dead end.
Is there a flow I am missing?
When you download it yourself to a clean directory (without the data already there), does it work *as is* at your end?

Again, thanks for your contribution.

**Comment by James4Deutschland** [comment]
Same error here. I am wondering whether there is a script to process the original data in `AIAlpha\sample_data\raw_data`.

**Comment by James4Deutschland** [comment]
Actually I have found the script which is named `bar_sample.py`.
In order to run that script, you need to copy and rename `sample_data` as `data`.
And after executing it, you can launch `run.py` without error.
If you want to run `pca_auto.py`, you can copy everything under `\data` and paste them into `\AIAlpha`.

**Comment by assaf-b** [comment]
Hi James,

  Thanks!  However if you'll check my original post you'll see that I actually tried bar_sample.py, but it needed a file by the name of price_vol.csv ...
How did you get around the missing price_vol.csv?

As for run.py, it just skips the preceding data preparation, assuming CSVs are present in the folders, so by planting CSVs with the proper names I can get it to run, however I wanted to follow the pipeline as designed by Vivek before I attempt modifying the pipeline..

Thanks

**Comment by VivekPa** [comment]
Hello, it should work now. The bar sampling was in another file, which was usually run before running run.py file.

**Comment by assaf-b** [comment]
Hi Vivek and thanks :)

I actually did try to run bar_sample.py before opening this issue (see my original post) and bar_sample.py failed on its own prereqs, so you're saying that now the updated run.py will take care of bar_sample.py's own prereqs?

Thanks!
