### ISSUE TITLE
processed_data/price_bars/dollar_bars.csv missing

### ISSUE THREAD

**Issue by ppete3** [VivekPa/AIAlpha#21]
I downloaded the project from Git on 7/31/2019. 
run.py has df = preprocess.make_features(file_path=f"sample_data/processed_data/price_bars/dollar_bars.csv", window=20,  
    csv_path="sample_data/processed_data/autoencoder_data", save_csv=True)
C:\_AI\AIAlpha-master\sample_data\processed_data\price_bars only has test 

can you help me?

**Comment by VivekPa** [comment]
Added the required code parts to run.py. Do check now.
