### ISSUE TITLE
Why not consider Volume as input?

### ISSUE THREAD

**Issue by liusida** [VivekPa/AIAlpha#9]
When I interviewed several professional traders, none of them would ignore the Volume information before making any decision. When they refer to a market signal, they will define it in both Price and Volume.

And if one is a high-frequent trader, Level 2 information is mandatory too.

So maybe you can add those to your model, hopefully that will increase the accuracy.

**Comment by VivekPa** [comment]
Hi, yes I have updated the model to consider various features including volume
